my_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taxis.urls')),

]

taxis/urls.py
from django.urls import path, reverse
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from .views import logout_view

class CustomLoginView(auth_views.LoginView):
    def get_success_url(self):
        return reverse('role_based_redirect')

urlpatterns = [
    path('', views.index, name='index'),
    #walo
    path('client/taxi_details/<int:taxi_id>/', views.taxi_detail, name='taxi_detail'), 
    path('view_reports/', views.view_reports, name='view_reports'),
    path('manage_users/', views.manage_users, name='manage_users'),

    #client
    path('create-booking/', views.create_booking, name='create_booking'),
    path('user-bookings/', views.user_bookings, name='user_bookings'),
    path('submit-review/', views.submit_review, name='submit_review'),
    path('list-reviews/', views.list_reviews, name='list_reviews'),
    path('client/cancel_reservation/<int:reservation_id>/', views.cancel_reservation, name='cancel_reservation'),
   
    #driver
    path('driver/assignments/', views.view_assignments, name='view_assignments'),
    path('driver/update_availability/', views.update_availability, name='update_availability'),
    path('driver/profile/', views.driver_profile, name='driver_profile'),
    path('contact-client/<int:booking_id>/', views.contact_client, name='contact_client'),
    path('signup-driver/', views.driver_signup, name='driver_signup'),
    path('driver/send_message/<int:booking_id>/', views.send_message, name='send_message'),

    #admin
    path('list-drivers/', views.list_drivers, name='list_drivers'),
    path('add-driver/', views.add_driver, name='add_driver'),
    path('manage_drivers/', views.manage_drivers, name='manage_drivers'), 
    path('edit_driver/<int:driver_id>/', views.edit_driver, name='edit_driver'),
    path('delete_driver/<int:driver_id>/', views.delete_driver, name='delete_driver'),

    path('manage_clients/', views.manage_clients, name='manage_clients'), 
    path('delete_client/<int:client_id>/', views.delete_client, name='delete_client'),
    path('edit-client/<int:client_id>/', views.edit_client, name='edit_client'),

    path('add_taxi/', views.add_taxi, name='add_taxi'),
    path('manage_taxis/', views.manage_taxis, name='manage_taxis'),
    path('edit_taxi/<int:taxi_id>/', views.edit_taxi, name='edit_taxi'),
    path('delete_taxi/<int:taxi_id>/', views.delete_taxi, name='delete_taxi'),
    path('list-taxis/', views.list_taxis, name='list_taxis'),
   
    path('manage-bookings/', views.manage_bookings, name='manage_bookings'),
    path('cancel-booking/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    path('modify-booking/<int:booking_id>/', views.modify_booking, name='modify_booking'),
    path('administrateur/assign_driver/<int:booking_id>/', views.assign_driver, name='assign_driver'),
    path('administrateur/unassigned_bookings/', views.unassigned_bookings, name='unassigned_bookings'),
    #connexion
    path('login/', auth_views.LoginView.as_view(template_name='taxis/registration/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='taxis/registration/login.html')),
    path('role_based_redirect/', views.role_based_redirect, name='role_based_redirect'),
    path('client/dashboard/', views.client_dashboard, name='client_dashboard'),
    path('driver/dashboard/', views.driver_dashboard, name='driver_dashboard'),
    path('administrateur/dashboard/', views.administrateur_dashboard, name='administrateur_dashboard'),
]

taxis/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser,AbstractBaseUser


class User(AbstractUser):
    CLIENT = 'client'
    DRIVER = 'driver'
    ADMINISTRATEUR = 'administrateur'

    ROLE_CHOICES = [
        (CLIENT, 'Client'),
        (DRIVER, 'Driver'),
        (ADMINISTRATEUR, 'Administrateur'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='client')
    def role_css_class(self):
        if self.role == self.CLIENT:
            return 'client'
        elif self.role == self.DRIVER:
            return 'driver'
        elif self.role == self.ADMINISTRATEUR:
            return 'administrateur'
        return ''
    # Ajoutez vos champs personnalisés si nécessaire
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        related_name='taxis_users'  # related_name distinct pour groups
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        related_name='taxis_users'  # related_name distinct pour user_permissions
    )
    def __str__(self):
        return self.username
    
class Driver(models.Model):
    name = models.CharField(max_length=100)
    license_number = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=255, default='Unknown')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    availability = models.BooleanField(default=True)
    def __str__(self):
        return self.user.username
    def __str__(self):
        return self.name
    def __str__(self):
        return self.user.get_full_name() 

class Taxi(models.Model):
    registration_number = models.CharField(max_length=50)
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, null=True, blank=True)
    brand = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    available = models.BooleanField(default=True)  # Assurez-vous que ce champ est défini correctement

    def __str__(self):
        return self.registration_number
    
#imkn supp reservation
class Reservation(models.Model):
    taxi = models.ForeignKey(Taxi, on_delete=models.CASCADE)
    passenger_name = models.CharField(max_length=100)
    pickup_location = models.CharField(max_length=200)
    dropoff_location = models.CharField(max_length=200)
    pickup_time = models.DateTimeField()
    dropoff_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.passenger_name} - {self.taxi}"
    def cancel(self):
        self.status = 'cancelled'
        self.save()



class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, related_name='bookings', null=True, blank=True)
    #taxi = models.ForeignKey(Taxi, on_delete=models.CASCADE,default=1)
    pickup_location = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    pickup_time = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    contact_number = models.CharField(max_length=15, null=True, blank=True)
    def __str__(self):
        return f"Booking for {self.user.username} at {self.pickup_time}"
    def cancel(self):
        self.status = 'cancelled'
        self.save()



class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    taxi = models.ForeignKey(Taxi, on_delete=models.CASCADE)
    rating = models.IntegerField()
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.taxi.registration_number} - {self.rating}'
    


class Assignment(models.Model):
    driver = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    details = models.TextField()

    def __str__(self):
        return f"{self.driver.username} - {self.date}"

class DriverProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    availability = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username
    
class Report(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    # Autres champs spécifiques aux rapports

    def __str__(self):
        return self.title
    
class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20)
    address = models.TextField()

    def __str__(self):
        return self.user.username
    
class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Message from {self.sender.username} to {self.receiver.username} for Booking {self.booking.id}"

taxis/forms.py
from django import forms
from .models import Taxi, Driver, Reservation,Booking ,Review,User,DriverProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models
from .models import User
from .models import Client
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
# forms.py
from django import forms
from .models import Driver

class UpdateAvailabilityForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ['availability']  # Add other fields if necessary

class CustomUserCreationForm(UserCreationForm):
    ROLE_CHOICES = [
        ('client', 'Client'),
        ('driver', 'Driver'),
        ('administrateur', 'Administrateur'),
    ]
    role = forms.ChoiceField(choices=ROLE_CHOICES)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'role')

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user

class AvailabilityForm(forms.ModelForm):
    class Meta:
        model = DriverProfile
        fields = ['availability']



class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    role = forms.ChoiceField(choices=User.ROLE_CHOICES, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'role']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.role = self.cleaned_data['role']
        if commit:
            user.save()
        return user

class TaxiForm(forms.ModelForm):
    class Meta:
        model = Taxi
        fields = ['registration_number','brand', 'model']

class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ['phone_number', 'address']

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['pickup_location', 'destination', 'pickup_time', 'contact_number']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['taxi', 'rating', 'comment']

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['phone_number', 'address']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Personnalisation des champs si nécessaire
        self.fields['phone_number'].label = 'Numéro de téléphone'
        self.fields['address'].label = 'Adresse'
        self.fields['address'].widget = forms.Textarea(attrs={'rows': 3})


class DriverSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = User.DRIVER
        if commit:
            user.save()
        return user       
    
class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'role') 
        user_id = forms.IntegerField(widget=forms.HiddenInput())  # Champ caché pour l'ID utilisateur
        username = forms.CharField(max_length=150)
        email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})  # Ajoutez des classes CSS si nécessaire
        self.fields['email'].widget.attrs.update({'class': 'form-control'})

    def clean_user_id(self):
        user_id = self.cleaned_data['user_id']
        if not User.objects.filter(id=user_id).exists():
            raise forms.ValidationError("Utilisateur non trouvé.")
        return user_id
    

class CancelBookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = []  # Ajoutez les champs spécifiques nécessaires pour annuler une réservation, comme 'status'

class ModifyBookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = []  # Ajoutez les champs spécifiques nécessaires pour modifier une réservation

    def __init__(self, *args, **kwargs):
        super(ModifyBookingForm, self).__init__(*args, **kwargs)
        # Personnalisez les champs ou ajoutez des validations si nécessaire


from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']

class AssignDriverForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['driver']

    driver = forms.ModelChoiceField(
        queryset=Driver.objects.all(),
        widget=forms.Select,
        label="Sélectionner un conducteur",
        empty_label="Sélectionner un conducteur"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['driver'].queryset = Driver.objects.all()
        self.fields['driver'].label_from_instance = lambda obj: f"{obj.user.username} ({obj.license_number})"

taxis/templates/taxis/client/cancel_reservation.html
<!-- templates/dashboard/cancel_reservation.html -->
{% extends 'taxis/base.html' %}

{% block title %}Annuler la Réservation{% endblock %}

{% block content %}
<h2>Annuler la Réservation</h2>
<p>Êtes-vous sûr de vouloir annuler cette réservation ?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Oui, annuler</button>
    <a href="{% url 'user_bookings' %}">Non, revenir en arrière</a>
</form>
{% endblock %}

taxis/templates/taxis/client/create_booking.html
<!-- templates/taxis/create_booking.html -->
{% extends 'taxis/base.html' %}

{% block title %}Créer une réservation{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Créer une nouvelle réservation</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_pickup_location">Lieu de prise en charge</label>
            {{ form.pickup_location }}
        </div>
        <div class="form-group">
            <label for="id_destination">Destination</label>
            {{ form.destination }}
        </div>
        <div class="form-group">
            <label for="id_pickup_time">Date de prise en charge</label>
            {{ form.pickup_time }}
        </div>
        <div class="form-group">
            <label for="id_contact_number">Numéro de contact</label>
            {{ form.contact_number }}
        </div>
        <button type="submit" class="btn btn-primary">Réserver</button>
    </form>
</div>
{% endblock %}

taxis/templates/taxis/client/list_reviews.html
<!-- templates/dashboard/list_reviews.html -->
{% extends 'taxis/base.html' %}

{% block title %}Liste des Avis{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Liste des Avis</h2>
    <div class="card-deck mt-4">
        {% for review in reviews %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ review.subject }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Avis de {{ review.user.username }} sur {{ review.taxi }}</h6>
                <p class="card-text">{{ review.comment }}</p>
                <p class="card-text text-muted">{{ review.created_at }}</p>
            </div>
        </div>
        {% empty %}
        <div class="card">
            <div class="card-body">
                <p class="card-text">Aucun avis trouvé.</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

taxis/templates/taxis/client/submit_review.html
<!-- taxis/templates/taxis/submit_review.html -->

{% extends 'taxis/base.html' %}

{% block title %}Soumettre un Avis{% endblock %}

{% block content %}
    <h2>Soumettre un Avis</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Soumettre</button>
    </form>
{% endblock %}

taxis/templates/taxis/client/user_bookings.html
{% extends 'taxis/base.html' %}

{% block title %}Mes Réservations{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Mes Réservations</h2>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Taxi</th>
                <th>Lieu de prise en charge</th>
                <th>Lieu de dépôt</th>
                <th>Heure de prise en charge</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for booking in bookings %}
                <tr>
                    <td>{{ booking.taxi.name }}</td>
                    <td>{{ booking.pickup_location }}</td>
                    <td>{{ booking.destination }}</td>
                    <td>{{ booking.pickup_time }}</td>
                    <td>
                        <a href="{% url 'cancel_reservation' booking.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Voulez-vous vraiment annuler cette réservation ?');">Annuler</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}